// Development

### Get all contacts
GET http://localhost:8080/contacts

### Get a single contact by id
GET http://localhost:8080/contacts/ql24FT8JETBzEUq9CSznvEYVXAxsyArG8imhOBVARelqzmBWlk

### Create a new contact
POST http://localhost:8080/contacts/ HTTP/1.1
content-type: application/json

{
  "firstName": "newFirst",
  "lastName": "newLast",
  "email": "new@email.com",
  "favoriteColor": "newColor",
  "birthday": "New 1, 2000"
}

### Update contact
PUT http://localhost:8080/contacts/Bqy5ky8e3oQDuEfFfoikkpReQBjvgoeoA3A0PfCq2j95aTYfAK
content-type: application/json

{
  "firstName": "updatedFirst",
  "lastName": "newLast",
  "email": "new@email.com",
  "favoriteColor": "newColor",
  "birthday": "New 1, 2000"
}

### Delete a single contact by id
DELETE http://localhost:8080/contacts/Bqy5ky8e3oQDuEfFfoikkpReQBjvgoeoA3A0PfCq2j95aTYfAK


// Prodiction

### Get all contacts
GET https://cse341-uq0r.onrender.com/contacts

### Get a single contact by id
GET https://cse341-uq0r.onrender.com/contacts/ql24FT8JETBzEUq9CSznvEYVXAxsyArG8imhOBVARelqzmBWlk

### Create a new contact
POST https://cse341-uq0r.onrender.com/contacts/ HTTP/1.1
content-type: application/json

{
  "firstName": "newFirst",
  "lastName": "newLast",
  "email": "new@email.com",
  "favoriteColor": "newColor",
  "birthday": "New 1, 2000"
}

### Update contact
PUT https://cse341-uq0r.onrender.com/contacts/ql24FT8JETBzEUq9CSznvEYVXAxsyArG8imhOBVARelqzmBWlk
content-type: application/json

{
  "firstName": "updatedFirst",
  "lastName": "newLast",
  "email": "new@email.com",
  "favoriteColor": "newColor",
  "birthday": "New 1, 2000"
}

### Delete a single contact by id
DELETE https://cse341-uq0r.onrender.com/contacts/2VGAUdsAXdiaKGRFjPH0fae7O9gLLho8efWGsNdXUvkFc0O0D4
