// Development

### Get all companies
GET http://localhost:8080/companies

### Get a single company by id
GET http://localhost:8080/companies/Je9weycEIqzUtdz0l1PJDk4VoGPTxx9JFBAoBEyd1lt9e6gPk8

### Create a new company
POST http://localhost:8080/companies/ HTTP/1.1
content-type: application/json

{
  "name": "Newly Created Company",
  "address": "New address WRONG",
  "city": "New city",
  "state": "New state",
  "zipCode": "New zip",
  "website": "http://www.lds.org",
  "phoneNumber": "208-555-4444",
  "email": "new@here.com"
}

### Update company
PUT http://localhost:8080/companies/TKKWcyTJjIi8T2LZFPDsr4GbhpGQEDMlKoymH8ePPP0j0Qr65B
content-type: application/json

{
  "name": "Newly Created Company",
  "address": "New address",
  "city": "New city",
  "state": "New state",
  "zipCode": "New zip",
  "website": "http://www.lds.org",
  "phoneNumber": "208-555-4444",
  "email": "new@here.com"
}

### Delete a single company by id
DELETE http://localhost:8080/companies/TKKWcyTJjIi8T2LZFPDsr4GbhpGQEDMlKoymH8ePPP0j0Qr65B

### Get all services
GET http://localhost:8080/services

### Get a single service by id
GET http://localhost:8080/services/ql24FT8JETBzEUq9CSznvEYVXAxsyArG8imhOBVARelqzmBWlk

### Create a new service
POST http://localhost:8080/services/ HTTP/1.1
content-type: application/json

{
  "name": "Newly Creted Service WRONG",
  "companyName": "New Company Name",
  "cost": "New Cost"
}

### Update service
PUT http://localhost:8080/services/Bqy5ky8e3oQDuEfFfoikkpReQBjvgoeoA3A0PfCq2j95aTYfAK
content-type: application/json

{
  "name": "Newly Creted Service",
  "companyName": "New Company Name",
  "cost": "New Cost"
}

### Delete a single service by id
DELETE http://localhost:8080/services/Bqy5ky8e3oQDuEfFfoikkpReQBjvgoeoA3A0PfCq2j95aTYfAK


// Production

### Get all companies
GET https://cse341-w3-4.onrender.com/companies

### Get a single company by id
GET https://cse341-w3-4.onrender.com/companies/ql24FT8JETBzEUq9CSznvEYVXAxsyArG8imhOBVARelqzmBWlk

### Create a new company
POST https://cse341-w3-4.onrender.com/companies/ HTTP/1.1
content-type: application/json

{
  "name": "Newly Created Company",
  "address": "New address WRONG",
  "city": "New city",
  "state": "New state",
  "zipCode": "New zip",
  "website": "http://www.lds.org",
  "phoneNumber": "208-555-4444",
  "email": "new@here.com"
}

### Update company
PUT https://cse341-w3-4.onrender.com/companies/ql24FT8JETBzEUq9CSznvEYVXAxsyArG8imhOBVARelqzmBWlk
content-type: application/json

{
  "name": "Newly Created Company",
  "address": "New address",
  "city": "New city",
  "state": "New state",
  "zipCode": "New zip",
  "website": "http://www.lds.org",
  "phoneNumber": "208-555-4444",
  "email": "new@here.com"
}

### Delete a single company by id
DELETE https://cse341-w3-4.onrender.com/companies/TqM87QP2kcSUR00sm7v2qxBg1R9OsP33AzKEA9CyR3QfN1EHhl

### Get all services
GET https://cse341-w3-4.onrender.com/services

### Get a single service by id
GET https://cse341-w3-4.onrender.com/services/ql24FT8JETBzEUq9CSznvEYVXAxsyArG8imhOBVARelqzmBWlk

### Create a new service
POST https://cse341-w3-4.onrender.com/services/ HTTP/1.1
content-type: application/json

{
  "name": "Newly Creted Service WRONG",
  "companyName": "New Company Name",
  "cost": "New Cost"
}

### Update service
PUT https://cse341-w3-4.onrender.com/services/ql24FT8JETBzEUq9CSznvEYVXAxsyArG8imhOBVARelqzmBWlk
content-type: application/json

{
  "name": "Newly Creted Service",
  "companyName": "New Company Name",
  "cost": "New Cost"
}

### Delete a single service by id
DELETE https://cse341-w3-4.onrender.com/services/2VGAUdsAXdiaKGRFjPH0fae7O9gLLho8efWGsNdXUvkFc0O0D4